---
kind: pipeline
name: example

steps:
- name: test
  image: meltwaterfoundation/drone-terrafy
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  commands:
  - apk add go build-base
  - cd terratest
  - terrapin -force -tf-version 0.12.21 -directory /usr/local/bin
  - cd test
  - go test -v -run TestAwsDnsRecordName

trigger:
  branch:
    include:
    - master
  event:
  - push
  - pull_request
---
kind: signature
hmac: 06fe1ecacae32cf2da4b91d1f7d57e1dcb051257a4b45137f63732c70dc00f46

...
